home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

bucket_url = [
    path("", views.BucketHomeView.as_view(), name="bucket"),
    path("delete_obj/<path:key>/", views.DeleteBucketObject.as_view(), name="delete_obj_bucket"),
    path("download_obj/<path:key>/", views.DownloadBucketObjectView.as_view(), name="download_obj_bucket"),
]

products_url = [
    path("", views.ProductsView.as_view(), name="products"),
    path("category/<slug:category_slug>/", views.ProductsView.as_view(), name="category_filter"),
    path("upload/", views.ProductUploadViewList.as_view(), name="upload_product"),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="product_detail"),
]

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("index/", views.ViewIndex.as_view(), name="index"),
    path("bucket/", include(bucket_url)),
    path("products/", include(products_url)),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("accounts.urls", namespace="accounts")),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def generate_unique_slug(name):
    base_slug = slugify(name)
    slug = base_slug
    counter = 1
    while Product.objects.filter(slug=slug).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    return slug


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("home:category_filter", args=[self.slug, ])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.slug])

home/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image', 'category']

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image', 'category']  # حتما category رو بیار

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from django.utils.text import slugify
from utils import IsAdminUserMixin
from . import tasks
from .models import Product, Category
from .forms import ProductForm


class HomeView(View):
    template_name = "base.html"

    def get(self, request):
        return render(request, self.template_name)


class ViewIndex(View):
    template_name = "home/index.html"

    def get(self, request):
        title = {}
        return render(request, self.template_name, {'title': title})


class BucketHomeView(IsAdminUserMixin, View):
    template_name = "home/bucket.html"

    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {"objects": objects})


class DeleteBucketObject(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.delete_object_task.delay(key)
        messages.success(request, "Your Delete Object The Perfect ... ")
        return redirect("home:bucket")


class DownloadBucketObjectView(IsAdminUserMixin, View):
    def get(self, request, key):
        tasks.download_object_task.delay(key)
        messages.success(request, "Your Download Perfect File ...", "info")
        return redirect("home:bucket")


class ProductsView(View):
    template_name = "home/products.html"

    def get(self, request, category_slug=None):
        products = Product.objects.all()
        categories = Category.objects.all()
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, self.template_name, {'products': products, 'categories': categories})
       


class ProductDetailView(View):
    template_name = "home/product_detail.html"

    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        return render(request, self.template_name, {'product': product})


class ProductUploadViewList(View):
    template_name = "home/upload_product.html"

    def get(self, request):
        form = ProductForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(product.name)
            product.save()
            return redirect('home:product_detail', slug=product.slug)
        return render(request, self.template_name, {'form': form})

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Delete</th>
        <th scope="col">Download</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in objects %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ obj.Key }}</td>
        <td>{{ obj.Size|filesizeformat }}</td>
        <td>
          <a href="{% url 'home:delete_obj_bucket' obj.Key|urlencode %}">Delete</a>
        </td>
        <td>
          <a href="{% url 'home:download_obj_bucket' obj.Key|urlencode %}">Download</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5" class="text-center">No objects found.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
{% endblock %}

{% block content %}
<h1>Welcome to the -- Index -- Page ---</h1>
{% endblock %}

home/templates/home/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-4 mb-4">
      <div class="card h-100" style="width: 18rem;">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top">
        <div class="card-body d-flex flex-column">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text text-muted">{{ product.description|truncatewords:20 }}</p>
          <p class="mt-auto fw-bold">Price: {{ product.price }} Toman</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/products.html
{% extends 'base.html' %} {% block content %}

<div class="container mt-2">
{% for category in categories %}
<a href="{{ category.get_absolute_url }}" class="btn btn-info"> {{category.name}}</a>
{% endfor %}
</div>
<br> <br>
<div class="container mt-4">
  <div class="row">
    {% for product in products %}
    <div class="col-md-4 mb-4">
      <div class="card" style="width: 15rem">
        <img
          src="{{ product.image.url }}"
          class="card-img-top"
          alt="{{ product.name }}"
        />
        <div class="card-body">
          <h5 class="card-title">
            {% if product.slug %}
            <a href="{% url 'home:product_detail' product.slug %}"
              >{{ product.name }}</a
            >
            {% else %} {{ product.name }} {% endif %}
          </h5>
          <p class="card-text">Price: {{ product.price }} Toman</p>
        </div>
      </div>
    </div>
    {% empty %}
    <p>No products available.</p>
    {% endfor %}
  </div>
</div>


      </h5>
    </div>
  </div>
</div>
 {% endblock %}

home/templates/home/upload_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h3>ثبت محصول جدید</h3>

    {% if form.errors %}
        <div class="alert alert-danger">
            <strong>Error!</strong> Please correct the errors below.
        </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Upload</button>
    </form>
</div>
{% endblock %}