accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path("", views.AccountView.as_view(), name="accounts"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("verify/", views.UserRegistrationCodeView.as_view(), name="verify_code"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

bucket_url = [
    path("", views.BucketHomeView.as_view(), name="bucket"),
    path("delete_obj/<path:key>/", views.DeleteBucketObject.as_view(), name="delete_obj_bucket"),
    path("download_obj/<path:key>/", views.DownloadBucketObjectView.as_view(), name="download_obj_bucket"),
]

products_url = [
    path("", views.ProductsView.as_view(), name="products"),
    path("category/<slug:category_slug>/", views.ProductsView.as_view(), name="category_filter"),
    path("upload/", views.ProductUploadViewList.as_view(), name="upload_product"),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="product_detail"),
]

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("index/", views.ViewIndex.as_view(), name="index"),
    path("bucket/", include(bucket_url)),
    path("products/", include(products_url)),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls", namespace="home")),
    path("account/", include("accounts.urls", namespace="accounts")),
]

templates/inc/messages.html
{% if messages %} {% for message in messages %}
<div
  class="alert alert-dismissible fade show m-3 {% if message.tags == 'success' %}alert-success {% elif message.tags == 'error' %}alert-danger {% elif message.tags == 'warning' %}alert-warning {% elif message.tags == 'info' %}alert-info {% else %}alert-secondary {% endif %}"
  role="alert"
>
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %}

templates/inc/navbar.html
<!-- inc/navbar.html -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
  <div class="container-fluid">
    
    <!-- دکمه موبایل -->
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- منو -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav"> <!-- ms-auto حذف شد -->
        <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'home:home' %}">
            <i class="fas fa-home me-1"></i> Home
          </a>
        </li>
        {% if request.user.is_authenticated %}
           </li>
          <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'accounts:logout' %}">
          <i class="fas fa-box-open me-1"></i> Logout
            </a>
        </li>
        {% else %}
            </li>
          <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'accounts:login' %}">
          <i class="fas fa-box-open me-1"></i> Login
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'accounts:register' %}">
            <i class="fas fa-user-plus me-1"></i> Register
          </a>
        </li>
        {% endif %}
        {% if request.user.is_admin %}
          <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'home:bucket' %}">
          <i class="fas fa-box-open me-1"></i> Bucket 
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'home:products' %}">
            <i class="fas fa-box-open me-1"></i> Products
          </a>
        </li>
                  <li class="nav-item">
          <a class="nav-link text-white mx-2" href="{% url 'home:upload_product' %}">
          <i class="fas fa-box-open me-1"></i> New Product
            </a>
        </li>
          </li>
        
     
      </ul>
    </div>
  </div>
</nav>